### ISSUE TITLE
Error: Cannot find module '@tailwindcss/aspect-ratio'

### ISSUE THREAD

**Issue by rizkiheryandi** [uasoft-indonesia/badaso-landy-theme#10]
**Describe the bug**
Error: Cannot find module '@tailwindcss/aspect-ratio'

**To Reproduce**
1. Install landy theme
2. Install and build JS CSS depedency
3. See error

**Expected behavior**
No error

**Screenshots**
<img width="740" alt="image" src="https://user-images.githubusercontent.com/25028868/190962018-ae4e2d83-2ebb-4928-9781-e980b8262422.png">

**Comment by abraham-yusuf** [comment]
how ti fix that?
just add dependencies
yarn add -D @tailwindcss/aspect-ratio
then, yarn dev. its work for me
